### ISSUE TITLE
Questions about the loss function and label generation

### ISSUE THREAD

**Issue by Jessie-jx** [Kshitizbansal/pointillism_rp_net#2]
Hi @Kshitizbansal , thank you for releasing the code.
I have two questions about some details in the code.

1. In _RP-net.py_, when calculating the Smooth-L1 loss between the ground truth and regressed bounding box parameters (line 325-331), I don't understand why _labels_binary_iou_select_ is multiplied by and _select_anchor_box_batch_select_ is subtracted from _gt_labels_bbox_. I thought the loss function should just be like _(x-gt_labels_bbox)_. The same question in the evalution process (line 425-431)
2. In _data_generator.py_, when generating labels, I am wondering why the label padding is needed (line 34).

I would really appreciate your reply.

**Comment by Kshitizbansal** [comment]
Hi,

1. The reason we multiply _labels_binary_iou_select_ is to only perform regression for the anchor boxes that have an IoU higher than the threshold with ground truth boxes. Further, _select_anchor_box_batch_select_ is subtracted from _gt_labels_bbox_ because we only want to predict the offset from the anchor box dimension and not the actual value of the dimension.

2. The reason for padding is that the number of GT labels is different for each frame. To ensure consistent sizes, we pad zeros to the tensor that has GT labels. Having these zeros do not affect the learning performance.
